StartupEvents.registry('item', event => {
    event.create('uncomplete_boiler', 'create:sequenced_assembly').displayName('Uncomplete Basic Engine')
    event.create('uncomplete_bomb_bay', 'create:sequenced_assembly').displayName('Uncomplete Bomb Bay')
    event.create('uncomplete_eco_engine', 'create:sequenced_assembly').displayName('Uncomplete Water Engine')
    event.create('uncomplete_engine', 'create:sequenced_assembly').displayName('Uncomplete Advanced Engine')
    event.create('uncomplete_enhanced_propeller', 'create:sequenced_assembly').displayName('Uncomplete Brass Propeller')
    event.create('uncomplete_gyroscope', 'create:sequenced_assembly').displayName('Uncomplete Gyroscope')
    event.create('uncomplete_heavy_crossbow', 'create:sequenced_assembly').displayName('Uncomplete Heavy Crossbow')
    event.create('uncomplete_hull', 'create:sequenced_assembly').displayName('Uncomplete Hull')
    event.create('uncomplete_improved_landing_gear', 'create:sequenced_assembly').displayName('Uncomplete Improved Landing Gear')
    event.create('uncomplete_industrial_gears', 'create:sequenced_assembly').displayName('Uncomplete Industrial Gears')
    event.create('uncomplete_nether_engine', 'create:sequenced_assembly').displayName('Uncomplete Lava Engine')
    event.create('uncomplete_propeller', 'create:sequenced_assembly').displayName('Uncomplete Large Propeller')
    event.create('uncomplete_hull_reinforcement', 'create:sequenced_assembly').displayName('Uncomplete Reinforced Hull')
    event.create('uncomplete_rotary_cannon', 'create:sequenced_assembly').displayName('Uncomplete Rotary Cannon')
    event.create('uncomplete_steel_boiler', 'create:sequenced_assembly').displayName('Uncomplete Steel Boiler')
    event.create('uncomplete_sturdy_pipes', 'create:sequenced_assembly').displayName('Uncomplete Sturdy Pipes')
    event.create('uncomplete_telescope', 'create:sequenced_assembly').displayName('Uncomplete Telescope')
} )